// Auto-generated icon registry. Vuetify is configured to use the mdi-svg
// iconset; templates reference icons via "$mdi-foo" aliases (with the $
// prefix telling Vuetify to look up the alias map below).
//
// To add a new icon: write `icon="$mdi-foo"` in a template, then re-run
// scripts/regenerate-icons.py — that script will rescan src/ for usages
// and rewrite this file.
import {
  mdiAccessPointNetwork,
  mdiAlert,
  mdiAlertCircle,
  mdiApi,
  mdiApple,
  mdiArrowLeftRight,
  mdiAutoFix,
  mdiBattery,
  mdiBatteryCharging,
  mdiCamera,
  mdiCellphone,
  mdiCellphoneArrowDown,
  mdiCheck,
  mdiCheckCircle,
  mdiChip,
  mdiClose,
  mdiCloudUpload,
  mdiCog,
  mdiCompare,
  mdiContentSave,
  mdiCropFree,
  mdiCursorMove,
  mdiDatabase,
  mdiDelete,
  mdiDeleteSweep,
  mdiDownload,
  mdiEye,
  mdiEyeOff,
  mdiFitToScreen,
  mdiFlash,
  mdiFlaskOutline,
  mdiFormatListNumbered,
  mdiGithub,
  mdiGooglePlay,
  mdiHomeAssistant,
  mdiImageEdit,
  mdiImageMultiple,
  mdiMagicStaff,
  mdiMonitor,
  mdiOpenInNew,
  mdiPalette,
  mdiPlus,
  mdiPowerPlugOff,
  mdiRefresh,
  mdiRestoreAlert,
  mdiRotateRight,
  mdiSd,
  mdiServer,
  mdiSleep,
  mdiSync,
  mdiTune,
  mdiUpdate,
  mdiUpload,
  mdiWifi,
  mdiWifiStrength1,
  mdiWifiStrength2,
  mdiWifiStrength3,
  mdiWifiStrength4,
  mdiZipBox,
} from "@mdi/js";

export const aliases = {
  "mdi-access-point-network": mdiAccessPointNetwork,
  "mdi-alert": mdiAlert,
  "mdi-alert-circle": mdiAlertCircle,
  "mdi-api": mdiApi,
  "mdi-apple": mdiApple,
  "mdi-arrow-left-right": mdiArrowLeftRight,
  "mdi-auto-fix": mdiAutoFix,
  "mdi-battery": mdiBattery,
  "mdi-battery-charging": mdiBatteryCharging,
  "mdi-camera": mdiCamera,
  "mdi-cellphone": mdiCellphone,
  "mdi-cellphone-arrow-down": mdiCellphoneArrowDown,
  "mdi-check": mdiCheck,
  "mdi-check-circle": mdiCheckCircle,
  "mdi-chip": mdiChip,
  "mdi-close": mdiClose,
  "mdi-cloud-upload": mdiCloudUpload,
  "mdi-cog": mdiCog,
  "mdi-compare": mdiCompare,
  "mdi-content-save": mdiContentSave,
  "mdi-crop-free": mdiCropFree,
  "mdi-cursor-move": mdiCursorMove,
  "mdi-database": mdiDatabase,
  "mdi-delete": mdiDelete,
  "mdi-delete-sweep": mdiDeleteSweep,
  "mdi-download": mdiDownload,
  "mdi-eye": mdiEye,
  "mdi-eye-off": mdiEyeOff,
  "mdi-fit-to-screen": mdiFitToScreen,
  "mdi-flash": mdiFlash,
  "mdi-flask-outline": mdiFlaskOutline,
  "mdi-format-list-numbered": mdiFormatListNumbered,
  "mdi-github": mdiGithub,
  "mdi-google-play": mdiGooglePlay,
  "mdi-home-assistant": mdiHomeAssistant,
  "mdi-image-edit": mdiImageEdit,
  "mdi-image-multiple": mdiImageMultiple,
  "mdi-magic-staff": mdiMagicStaff,
  "mdi-monitor": mdiMonitor,
  "mdi-open-in-new": mdiOpenInNew,
  "mdi-palette": mdiPalette,
  "mdi-plus": mdiPlus,
  "mdi-power-plug-off": mdiPowerPlugOff,
  "mdi-refresh": mdiRefresh,
  "mdi-restore-alert": mdiRestoreAlert,
  "mdi-rotate-right": mdiRotateRight,
  "mdi-sd": mdiSd,
  "mdi-server": mdiServer,
  "mdi-sleep": mdiSleep,
  "mdi-sync": mdiSync,
  "mdi-tune": mdiTune,
  "mdi-update": mdiUpdate,
  "mdi-upload": mdiUpload,
  "mdi-wifi": mdiWifi,
  "mdi-wifi-strength-1": mdiWifiStrength1,
  "mdi-wifi-strength-2": mdiWifiStrength2,
  "mdi-wifi-strength-3": mdiWifiStrength3,
  "mdi-wifi-strength-4": mdiWifiStrength4,
  "mdi-zip-box": mdiZipBox,
};
